### PR TITLE
address now contains non-empty string

### LINKED ISSUE #1: "address" prop is empty in Resolved BonjourEvent from dart BonjourBinding searchForService() stream
I think I found the problem in msgport_adaptar.cpp. 

Unfortunately, this still doesn’t return the port number.

Great dart package. Exactly what I've been looking for on windows.

### PR DESCRIPTION
**Pull request by LewisHolliday**
Potentially fixes #1

### CODE REVIEW

**Comment by Piero512** [comment]
Hey, this is very nice. Wasn't really expecting contributors just yet. Can I ask why are you interested in this repo? 

Honestly last time I had time for it I barely got it to work, so I haven't really used it.

Last time I checked it, I had to use some more internal state to match up with [Bonsoir](https://pub.dev/packages/bonsoir) expectations, so I left it for some other day.

**Comment by LewisHolliday** [comment]
Oh I'm not even familiar with bonjour or zeroconf (_yet_).
I'm trying to find the IP address & port number of debug enabled Android devices on _adb-tls-connect._tcp in order to auto connect without manually typing out the IP & port each time. I ultimately want to make a basic adb GUI in flutter, but haven't had much luck finding any dns_sd abstractions on windows.

**Comment by Piero512** [comment]
You can use [multicast_dns](https://pub.dev/packages/multicast_dns) package to resolve services through multicast DNS directly. I just really created this package because I wanted to practice some ReceivePort on FFI. Hopefully with the advancement of dart:io and dart ffi a companion c library won't be necessary.

**Comment by LewisHolliday** [comment]
Ah that's cool. I actually already tried that package but unfortunately it seems to be broken on windows due to https://github.com/flutter/flutter/issues/53477. 
I've tried all that pub.dev has to offer including [flutter_nsd](https://pub.dev/packages/flutter_nsd) which contrary to its platform listing, doesn't support windows. Unless I've missed something within these packages I'm going to have to wait for advancements in dart:io and dart:ffi like you say. Thus far, this seems to be the only package that returns an IP address on windows.
Thank you for the suggestion.

**Comment by Piero512** [comment]
Well, I wrote a nicer fix for the IP issue by actually allocating instead of relying on std::string buffer's, so I'm going to close this PR. Thanks anyways.

**Pull request closed without merging**
